<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Ofdrw.Net.Core/Ofdrw.Net.Core.csproj" />
    <ProjectReference Include="../../src/Ofdrw.Net.Graphics.SkiaSharp/Ofdrw.Net.Graphics.SkiaSharp.csproj" />
    <ProjectReference Include="../../src/Ofdrw.Net.Packaging/Ofdrw.Net.Packaging.csproj" />
    <ProjectReference Include="../../src/Ofdrw.Net.Reader/Ofdrw.Net.Reader.csproj" />
  </ItemGroup>
  <ItemGroup><None Include="../../e2e/Ofdrw.Net.Converter.Pdf.E2E/testdata/fonts/*.ttf" Link="fonts/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
  <ItemGroup><None Include="../../e2e/Ofdrw.Net.SkiaSharp.E2E/testdata/fonts/*.ttf" Link="style-fonts/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
