namespace Ofdrw.Net.Layout.Graphics;

/// <summary>Resource limits copied when a graphics context is created. Contexts are not thread safe.</summary>
public sealed class OfdGraphicsOptions
{
    /// <summary>Maximum total elements on the target page, including pre-existing elements.</summary>
    public int MaxPageElements { get; set; } = 100_000;
    /// <summary>Maximum commands in any drawn or clipped path.</summary>
    public int MaxPathCommands { get; set; } = 100_000;
    /// <summary>Maximum cumulative characters drawn by this context.</summary>
    public long MaxTextCharacters { get; set; } = 1_000_000;
    /// <summary>Maximum cumulative serialized path and clip characters generated by this context.</summary>
    public long MaxGeometryCharacters { get; set; } = 16_000_000;
    /// <summary>Maximum number of saved states.</summary>
    public int MaxSavedStates { get; set; } = 64;
    /// <summary>Maximum simultaneous clip intersections.</summary>
    public int MaxClipRegions { get; set; } = 32;
}
